on:
  repository_dispatch:
    types: [on-demand-test]

jobs:
  echo_message:
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
